export const SHOW_TABLE = "SHOW_TABLE" 

export const ADD_NEW  ='ADD_NEW'

export const TOGGLE_FORM = 'TOGGLE_FORM'

export const CLOSE_FORM = 'CLOSE_FORM'

export const OPEN_FORM = 'OPEN_FORM'

export const CHANGE_STATUS = 'CHANGE_STATUS'

export const DELETE_BUTTON = 'DELETE_BUTTON'

export const PUSH_CONTENT_TO_FORM = 'PUSH_CONTENT_TO_FORM'

export const DEFAULT_CONTENT_TO_FORM = 'DEFAULT_CONTENT_TO_FORM'

export const TRANSFER_DATA_FROM_FORM_TO_TABLE = 'TRANSFORM_DATA_FROM_FORM_TO_TABLE'

export const QUICK_LOOKUP_TABLE  ='QUICK_LOOKUP_TABLE'

export const SEARCH_FROM_CONTROL = 'SEARCH_FROM_CONTROL'

export const SORT_BY = 'SORT_BY'
